#Nuclear Fission Package Toml



[project]
name = "fission"
version = "1.0.0"
dependencies = [
   "numpy",
]
authors = [
  { name="Kevin Mesta", email="kmmesta@syr.edu" },
  { name="Sara Talebi", email="stalebi@syr.edu" },
]
description = "Nuclear fission reaction simulation package"
readme = "README.txt"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.scripts]
example_script = "fission:main_program"
